#!/usr/bin/env python3
"""Validate the structural contract of a tri-research Markdown report."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REFERENCE_RE = re.compile(r"^\[(\d+)]\s+(.+)$", re.MULTILINE)
INLINE_RE = re.compile(r"\[(\d+)]")
URL_RE = re.compile(r"https?://\S+")
CHINESE_RE = re.compile(r"[\u4e00-\u9fff]")
ENGLISH_RE = re.compile(r"\b[A-Za-z]{4,}\b")


def validate(text: str, min_sources: int) -> list[str]:
    errors: list[str] = []
    required_headings = ("## TL;DR", "## 参考文献", "## 搜索与降级状态")
    for heading in required_headings:
        if heading not in text:
            errors.append(f"missing required heading: {heading}")

    references = {int(number): entry for number, entry in REFERENCE_RE.findall(text)}
    if len(references) < min_sources:
        errors.append(f"expected at least {min_sources} references, found {len(references)}")

    if references:
        expected = list(range(1, max(references) + 1))
        actual = sorted(references)
        if actual != expected:
            errors.append(f"reference numbers are not consecutive: {actual}")

    reference_urls: dict[int, str] = {}
    for number, entry in sorted(references.items()):
        url_match = URL_RE.search(entry)
        if not url_match:
            errors.append(f"reference [{number}] has no URL")
        else:
            reference_urls[number] = url_match.group(0).rstrip(".,;:)]}>").lower()
        if not re.search(r"\bTier:\s*[123]\b", entry):
            errors.append(f"reference [{number}] has no valid Tier")
        if not re.search(r"\bFound by:\s*[^—\n]+", entry):
            errors.append(f"reference [{number}] has no Found by metadata")

    unique_urls = set(reference_urls.values())
    if len(unique_urls) < len(reference_urls):
        duplicate_numbers = sorted(
            number
            for number, url in reference_urls.items()
            if list(reference_urls.values()).count(url) > 1
        )
        errors.append(f"reference URLs are not unique: {duplicate_numbers}")
    if len(unique_urls) < min_sources:
        errors.append(
            f"expected at least {min_sources} unique reference URLs, found {len(unique_urls)}"
        )

    body = text.split("## 参考文献", 1)[0]
    cited = {int(number) for number in INLINE_RE.findall(body)}
    missing = sorted(cited - set(references))
    if missing:
        errors.append(f"inline citations have no reference entries: {missing}")
    unused = sorted(set(references) - cited)
    if unused:
        errors.append(f"reference entries are not cited in the body: {unused}")

    if not CHINESE_RE.search(text):
        errors.append("report has no Chinese-language coverage")
    if not ENGLISH_RE.search(text):
        errors.append("report has no English-language coverage")

    status_section = text.split("## 搜索与降级状态", 1)
    if len(status_section) == 2 and not re.search(
        r"available|unavailable|quota_exhausted", status_section[1]
    ):
        errors.append("search status section has no normalized channel status")

    forbidden = ("generated by AI", "由 AI 撰写", "AI 生成水印")
    for marker in forbidden:
        if marker.lower() in text.lower():
            errors.append(f"forbidden generation marker found: {marker}")
    return errors


def create_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("report", type=Path)
    parser.add_argument("--min-sources", type=int, default=10)
    return parser


def main() -> int:
    args = create_parser().parse_args()
    if not args.report.is_file():
        print(f"ERROR:report does not exist: {args.report}", file=sys.stderr)
        return 1
    errors = validate(args.report.read_text(encoding="utf-8"), args.min_sources)
    if errors:
        for error in errors:
            print(f"ERROR:{error}", file=sys.stderr)
        return 1
    print(f"OK:validated {args.report} with at least {args.min_sources} sources")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
